name: "Node Build"
description: "Install, test, and build Node app"

runs:
  using: "composite"
  steps:
    - name: Install deps
      run: npm install
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash

    - name: Build app
      run: npm run build
      shell: bash
